depend: [ProtocolLib,PowerNBT]
name: CustomEnchant
main: fr.enchantments.custom.loader.PluginLoader
version: 1.6.2
commands:
   setitemname:
      description: Ceci est une commande demonstration.
      permission: customenchantdebug.setitemname
      usage: /setitemname [player]
   addenchant:
      description: Ceci est une commande demonstration.
      permission: customenchantdebug.addenchant
      usage: /addenchant