depend: [ProtocolLib,PowerNBT]
name: CustomEnchant
main: fr.enchantments.custom.loader.PluginLoader
version: 1.6.2
commands:
   listenchants:
      description: Ceci est une commande demonstration.
      permission: customenchantdebug.listenchants
      usage: /listenchants
   addenchant:
      description: Try to add an enchant to the item in hand.
      permission: customenchantdebug.addenchant
      usage: /addenchant [id<given by /listenchants>] [level>0]